user nginx;
worker_processes auto;
pid /var/run/nginx.pid;


events {
    worker_connections 1024;
}


http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # Define el balanceador de carga
    upstream django_server {
        server web:8000;
        # server web:8001 weight=5; # weight=5 => significa que tendrá mas peso/importancia
        # server web:8002;
    }

    # Servidor HTTP interno para la app
    server {
        listen 80;
        server_name localhost;

        # 🔒 Bloquear acceso a .git/
        location ~ /\.git {
            deny all;
        }

        location ~ /\.env {
            deny all;
        }

        # Manejo de archivos estáticos
        location /static/ {
            alias /code/static/;
            expires 1y; # Cachea estáticos por un año
            add_header Cache-Control "public, max-age=31536000";
        }

        location /media/ {
            alias /code/media/;
            expires 1y; # Cachea estáticos por un año
            add_header Cache-Control "public, max-age=31536000";
        }

        location / {
            proxy_pass http://django_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 60s;
            proxy_read_timeout 60s;
            proxy_send_timeout 60s;
            proxy_buffering on;
            proxy_buffers 16 4k;
            proxy_buffer_size 8k;
        }

        # Configuración adicional para WebSockets
        location /ws {
            proxy_pass http://django_server; # this magic is needed for WebSocket
            proxy_http_version  1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}