version: '3.9'

services:
  # ----------------------------
  # Base de datos PostgreSQL
  # ----------------------------
  db:
    image: postgres:14.10
    container_name: postgresql
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
          - proxy_network


  # ----------------------------
  # Interfaz gráfica de Postgres
  # ----------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8085:80" # Cambiado para evitar conflictos con Nginx
    depends_on:
      - db

  # ----------------------------
  # Cache / Broker (Redis)
  # ----------------------------
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    expose:
      - "6379"
    networks:
      - proxy_network


  # ----------------------------
  # Aplicación Django principal
  # ----------------------------
  web:
    build: .
    container_name: django_app
    restart: always
    # command: daphne -b 0.0.0.0 -p 8000 BienesRaices.asgi:application
    volumes: # Persistencia de datos del codigo de programación
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
    env_file:
      - .env  # Variables de entorno
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - DJANGO_SETTINGS_MODULE=BienesRaices.settings  # Websockets
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    networks:
      - proxy_network
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn BienesRaices.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  # ----------------------------
  # Proxy inverso Nginx
  # ----------------------------
  nginx:
    image: nginx:latest
    container_name: nginx_raices
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf  # Configuración de Nginx
      - static_volume:/app_facturas/staticfiles:ro  # Mapea el volumen de estáticos como solo lectura
      # - media_volume:/app_facturas/mediafiles:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mapea certificados SSL generados por Certbot
    depends_on:
      - web
    ports:
      - "8400:80" # En vez de depender de una IP interna, mapeao el puerto del contenedor
    networks:
      - proxy_network
    

volumes:
  db_data:
  static_volume:
  media_volume:


networks:
  proxy_network:
    external: true