# Generated by Django 4.2.10 on 2024-05-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=123456789),
            preserve_default=False,
        ),
    ]
