# Generated by Django 4.2.10 on 2024-05-27 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_testimoniales_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoniales',
            name='contenido',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testimoniales',
            name='usuario',
            field=models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
