# Generated by Django 4.2.10 on 2024-05-27 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_testimoniales_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimoniales',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
