# Generated by Django 4.2.10 on 2024-04-11 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedades',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
